# Python Short cuts for scenarios

### [Location of python packages](https://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory)

In [1]:
python -m site

SyntaxError: invalid syntax (<ipython-input-1-4226d5725fba>, line 1)

# List

#### Set to List

In [1]:
a = set([1,2,3,4,1,4])
list(a)
#a.tolist() #Doesn't work

[1, 2, 3, 4]

### Check if one of a number of elements in list

In [3]:
a = [1,2,3,4]
b = [2,7]
print(any(x in a for x in b))

True


### Set (Add to a set)

In [1]:
a = set()
for each in "mississippi":
    a.add(each)
a

{'i', 'm', 'p', 's'}

### zip - Change two values simultaneously in a single loop

In [2]:
alist = ['a1', 'a2', 'a3']
blist = ['b1', 'b2', 'b3']
for a, b in zip(alist, blist):
    print (a, b)

a1 b1
a2 b2
a3 b3


### Find the elements match in corresponding locations of two lists equal sized

In [3]:
a = [1,2,3,4,7,6]
b = [3,2,6,8,7,6]
[i for i,j in zip(a,b) if i==j]

[2, 7, 6]

In [4]:
### Checking List Equality
alist == blist

False

#### Flatten Multidimentional List to 1D list (Works fullly for list of lists)

In [5]:
import itertools
l = [[[0]],[6,7],[4,6,8],[[9],[80]]]
list(itertools.chain(*l))

[[0], 6, 7, 4, 6, 8, [9], [80]]

In [ ]:
# if 2-dimensional
result['id'] = [eachid for each in ids for eachid in each] 

### Permutations

In [3]:
import itertools
a = [1,2,3]
list(itertools.permutations(a)),list(itertools.combinations(a,2)) 

([(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)],
 [(1, 2), (1, 3), (2, 3)])

# NUMPY

In [2]:
import numpy as np
na = np.array([[1,3,4,5],[4,6,1,7],[3,2,6,88]])

### Specific column selection 
https://stackoverflow.com/questions/8386675/extracting-specific-columns-in-numpy-array

In [7]:
print (na[:,1:3]) # columns from 1 upto 3-1
print (na[:,[1,3]]) #columns 1 and 3

[[3 4]
 [6 1]
 [2 6]]
[[ 3  5]
 [ 6  7]
 [ 2 88]]


### Select rows of a numpy array having a value in any column. Display any 3 specified columns
https://stackoverflow.com/questions/23911875/select-certain-rows-condition-met-but-only-some-columns-in-python-numpy

In [8]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,2,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  2 12]]


In [9]:
a[:,] == 2
#np.where(a[]==2)

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

### Number of Matches in two 1D array

In [3]:
goldY = np.array([1,2,1,1,2,1,3,3,3,3,2,1,2])
predY = np.array([1,2,3,1,1,1,3,1,3,3,2,1,1])
np.count_nonzero(predY == goldY)

9

### ARGMAX N

In [9]:
import numpy as np
a = np.array([4,5,2,1,8,0,3])
#Argsort orders from least to max values
a.argsort()[-3:][::-1]

array([4, 1, 0])

### ARGPARSE

In [11]:
import argparse

def main():
    parser = argparse.ArgumentParser()
    
    parser.add_argument("--eval_batch_size",default=16,type=int,required=False,help="Test batch size")
    parser.add_argument("--data_dir",default=None,type=str,required=True, help="Path of the Input test file")
    parser.add_argument("--no_cuda",default="False")
    parser.add_argument("--do_eval",action="store_true",help="Whether to use pretrained or not")
    
    args = parser.parse_args()
    
    print (args.eval_batch_size, args.data_dir, args.no_cuda, args.do_eval)

In [12]:
#Call by running ''' python filename.py --eval_batch_size 32 --do_eval --data_dir data/a/'''

### ARGMAX for LIST

In [13]:
p = [2,3,7,9,1,4,8,0]
maxp = max(p)
maxIdx = p.index(maxp)
print (maxIdx)

3


### APPEND TO numpy array in for loops

In [2]:
arrayA = np.empty((0,700))
arrayB = np.empty((0,700))
index = []
cosineSentSim = []
for idx, dataTokens in enumerate(zip(aTokens, bTokens)):
    index.append(idx)
    tokenizedA = " ".join(dataTokens[0])
    tokenizedB = " ".join(dataTokens[1])
    #print (tokenizedA,"\n",tokenizedB)
    sentenceVectorA = model.embed_sentence(tokenizedA)
    sentenceVectorB = model.embed_sentence(tokenizedB)
    arrayA = np.append(arrayA, sentenceVectorA,axis=0)
    arrayB = np.append(arrayB, sentenceVectorB,axis=0)
    #print (arrayA.shape, arrayB.shape)
    
    
    cosineSim = 1 - distance.cosine(sentenceVectorA, sentenceVectorB)
    cosineSentSim.append(cosineSim)
    #print('cosine similarity:', cosine_sim)

    #input("WAIT")

NameError: name 'np' is not defined

In [3]:
# Clipping / Clamp
numpy.clip(-4,0,3)

NameError: name 'numpy' is not defined

## DICTIONARY

#### Keys and values

In [14]:
a = {'a':1,'c':4,'b':3}
print(a.keys(),type(a.keys()),list(a.keys()))
print(a.values(),list(a.values()))

dict_keys(['a', 'c', 'b']) <class 'dict_keys'> ['a', 'c', 'b']
dict_values([1, 4, 3]) [1, 4, 3]


### Reverse key values dictionaries

In [8]:
inv_map = {v: k for k, v in my_map.items()}

NameError: name 'my_map' is not defined

### Dictionary Sort Based on Values

In [2]:
import operator
import collections
sortedAadj = sorted(aadjective.items(), key=operator.itemgetter(1),reverse=True)
aadjective = collections.OrderedDict(sortedAadj)

NameError: name 'aadjective' is not defined

### Get dictionary keys corresponding to max values of keys

In [9]:
max_keys = [keys for keys,values in d.items() if values == max(d.values)]

NameError: name 'd' is not defined

## UNICODE and STRING NORMALIZATION

In [15]:
# Turn a Unicode string to plain ASCII, thanks to
# https://stackoverflow.com/a/518232/2809427
def unicodeToAscii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
    )

# Lowercase, trim, and remove non-letter characters


def normalizeString(s):
    s = unicodeToAscii(s.lower().strip())
    s = re.sub(r"([.!?])", r" \1", s)
    s = re.sub(r"[^a-zA-Z.!?]+", r" ", s)
    return s

### Important Basics

In [3]:
a = "Hi"
a = 9 # allowed
b = "hello"
b[1]='i' #not allowed //String objects immutable

TypeError: 'str' object does not support item assignment

### Replace String

In [4]:
s = 'one two one two one'

print(s.replace(' ', '-'))

one-two-one-two-one


In [4]:
TestMode = True
def some_function():
  global TestMode
  TestMode = False
some_function()
print(TestMode) #<--Returns False For assigning a new value to a global variable from a function

False


In [8]:
a=9,2,3
print (a) # Returns tupple

(9, 2, 3)


In [13]:
# Numeric Operation
print(2//3) # Numeric division [floor]
print(2**3) # Exponentiation
print('A'*3) #Str repeatation
y = 'Abc'
print (y[:2],y[1:],y[:-2],y[-2:])
x = 'abc'
print(x[::-1]) #Reverse

0
8
AAA
Ab bc A bc
cba


In [21]:
#Garbage collection
import gc
collected_objects = gc.get_objects()
co = gc.collect()
print (co,collected_objects[0])

0 [<_ast.Expr object at 0x7fbe6808a828>]


### PATH Related

#### [Change the root path](https://stackoverflow.com/questions/1432924/python-change-the-scripts-working-directory-to-the-scripts-own-directory)

In [4]:
import os
print (os.getcwd())
os.chdir('/Users/kuntal/Python-cheat-sheets')
print (os.getcwd())
#This path should be relative to the root directory just set
embedding = "data/embeddings/pubmed_s100w10_min.bin"

/Users/kuntal/Python-cheat-sheets
/Users/kuntal/Python-cheat-sheets


### Rounding Up a list of scores to nearest whole number

In [1]:
def round_half_up(n, decimals=0):
    multiplier = 10 ** decimals
    return int(np.floor(n*multiplier + 0.5) / multiplier)

### Run Perl scripts in Python

In [1]:
! perl "data/train/raw/correlation-noconfidence.pl" "output/RandomForestRegression/testgs.txt" "output/RandomForestRegression/testsys.txt"

Can't open perl script "data/train/raw/correlation-noconfidence.pl": No such file or directory


### Convert TSV to CSV

In [3]:
import csv

with open('D:/AddressEvaluation/NAD/NAD.csv','r') as csvin, open('D:/NAD.txt', 'w') as tsvout:
    csvin = csv.reader(csvin)
    tsvout = csv.writer(tsvout, delimiter='\t')

    for row in csvin:
        tsvout.writerow(row)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/AddressEvaluation/NAD/NAD.csv'

In [4]:
a= [1,2,3,4]

In [5]:
a[2,3,0,1]

TypeError: list indices must be integers or slices, not tuple

## [Iterators](https://www.datacamp.com/community/tutorials/python-iterator-tutorial)

is an object of class which implements \_\_next__(). Purpose to call next() to get the next element

## Iterables

is an object that can return an iterator. Purpose is to return all of its element.
* Iterable will have two methods
    * \_\_iter__() : returns the iterator
    * \_\_next__() : helps iterator to find the next element
* Iterable class will have \_\_iter__ return self. Means iterable class both an iterable and its own iterator

In [6]:
a = {1,2,3}
b_iterator = iter(a)
print(type(a))            #Iterable
print(type(b_iterator))   #Iterator

<class 'set'>
<class 'set_iterator'>


### an iterator

In [9]:
class Series():
    
    def __init__(self, low, high):
        self.low = low
        self.high = high
        
    def __iter__(self):
        return self
        
    def __next__(self):
        if self.low > self.high:
            raise StopIteration
            
        self.low+=1
        return self.low - 1
        

In [11]:
print (Series(1,5))
print (list(Series(1,5)))

[1, 2, 3, 4, 5]


### Containers

Objects that hold data. Can perform membership tests on them  ( if 1 in [1,2,3] )

### Generators

In [22]:
def series_generator(low, high):  #Generator functions
    while (low < high):
        yield low                 #returns the value and wait for the next value being called
        low+=1
    
a = []
for i in list(series_generator(1,10)):
    #print (i) #wont show all
    a.append(i)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


Geneartor helps to use memory efficiently. Lazy factory concept. Produce one value and waits

In [26]:
x = [i for i in range(10)]
print (x)
print (type(x))   #Generator

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


```python
def some_function():
    result = []
    for ... in ...:
        result.append(x)
    return result

Can be replaced with 

def iterate_over():
    for ... in ...:
        yield x
        ```

### Find root words between two sentences (differentiating words)

In [1]:
def getRootWord(s):
    a = s['choice0']
    b = s['choice1']
    a = a.split()
    b = b.split()

    prefix = os.path.commonprefix([a,b])
    suffix = os.path.commonprefix([a[::-1],b[::-1]])[::-1]
    roota = a[len(prefix):len(a)-len(suffix)]
    rootb = b[len(prefix):len(b)-len(suffix)]
    s['roota'] = " ".join(roota)
    s['rootb'] = " ".join(rootb)
    s['rootasize'] = len(roota)
    s['rootbsize'] = len(rootb)
    return s

## Zip(*A) # create string taking columns of each (unzip)

In [2]:
name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha" ]

In [3]:
list(zip(*name))

[('M', 'N', 'S', 'A'),
 ('a', 'i', 'h', 's'),
 ('n', 'k', 'a', 't'),
 ('j', 'h', 'm', 'h'),
 ('e', 'i', 'b', 'a')]

In [6]:
["".join(list(each)) for each in list(zip(*name))]

['MNSA', 'aihs', 'nkat', 'jhmh', 'eiba']

### zip(*a) converts rows into columns and columns in to rows

In [17]:
a = [[3,0,8,4],[2,4,5,7],[9,2,6,3],[0,3,1,0]]
print(max(a))
print(list(zip(*a)))
max(list(zip(*a)))

[9, 2, 6, 3]
[(3, 2, 9, 0), (0, 4, 2, 3), (8, 5, 6, 1), (4, 7, 3, 0)]


(8, 5, 6, 1)

### splits string into char array

In [18]:
a = "abcs"
list(zip(*a))[0]

('a', 'b', 'c', 's')

### [List to dictionary with index](https://stackoverflow.com/questions/36459969/python-convert-list-to-dictionary-with-indexes)

In [8]:
lst = ['A','B','C']
{k: v for v, k in enumerate(lst)}


{'A': 0, 'B': 1, 'C': 2}

In [16]:
### Morse code
letter = [".-","-...","-.-.","-..",".","..-.","--.","....","..",".---","-.-",".-..","--","-.","---",".--.","--.-",".-.","...","-","..-","...-",".--","-..-","-.--","--.."]
letterdict = {chr(idx+ord('a')): each for idx, each in enumerate(letter)}

## Random number generation

In [2]:
# Generate 10 random numbers between 1 and 21 inclusive (may not be unique)
import random
for each in range(10):
    print(random.randint(1,21))

17
20
21
13
8
4
6
14
12
13


In [6]:
# Generate 2 randome numbers between 0 and 21 (unique)
random.sample(range(0,21),2)

[4, 18]

In [7]:
# select n random numbers from list
ans_train_data_selected = random.sample(list_a, n)

NameError: name 'random' is not defined

### Numpy load / save to files

In [ ]:
from numpy import savetxt
# define data
data = asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
# save to csv file
savetxt('data.csv', data, delimiter=',')

from numpy import loadtxt
data = loadtxt('data.csv', delimiter=',')


### Jsonlines Read

In [4]:
import jsonlines
all_bin = []
with jsonlines.open(os.path.join(dir,'006124ad6fc6c5e6dc03546fd77c5976.jsonl'),'r') as fr:
    for each in fr:
        all_bin.append(each)

NameError: name 'os' is not defined

### Jsonlines Write

In [2]:
with jsonlines.open(outfname,'w') as fo:
    for i in range(0,len(data),3):
        idx = 'ai2-'+str(idx_count)
        ques = data[i].strip()
        ans = data[i+1].strip("\n")
        expr = data[i+2].strip("\n").split("=")[1].strip()
        idx_count += 1
        fo.write({'idx':idx,'ques':ques,'ans':ans,'expr':expr})

NameError: name 'jsonlines' is not defined

### Json read

In [3]:
with open(file, encoding='utf-8-sig') as fh:
    json_data = json.load(fh)

NameError: name 'file' is not defined

### Count the number of  each elements

In [1]:
a =  [3, 4, 3, 4, 3, 5, 2, 4 ,3, 5, 2]
import collections
collections.Counter(a)

Counter({3: 4, 4: 3, 5: 2, 2: 2})

### Binning a set of elements

In [67]:
slices = np.linspace(0, 140, 8, True).astype(np.int)

In [68]:
# slices=np.insert(slices,0,-999)
slices

array([  0,  20,  40,  60,  80, 100, 120, 140])

In [70]:
np.digitize([0,1,20,21, 19,22,34,55,11,78,90],slices,right=True)

array([0, 1, 1, 2, 1, 2, 2, 3, 1, 4, 5])

### Finding the most repeated element of a list - Counter

In [4]:
collections.Counter(each_cluster_meal_amounts).most_common(1)

NameError: name 'each_cluster_meal_amounts' is not defined

### Finding n least repeated element of a list - Counter

In [13]:
least_common_clusters = dbscan_allotments_distribution.most_common()[:-n-1:-1]

NameError: name 'dbscan_allotments_distribution' is not defined

### 2D np array from two 1D array

In [9]:
import numpy as np
x = np.random.randn(5)
y = np.random.randn(5)

np.concatenate((x.reshape(-1,1),y.reshape(-1,1)),axis=-1)

array([[ 0.55769858, -0.48313678],
       [-1.07882395, -2.34370362],
       [ 0.02167433, -1.2091704 ],
       [ 0.84419003, -0.69578094],
       [-0.09088648,  0.29482994]])

### Sort list element based on nth element items

In [11]:
x = [(1,4,6),(2,8,1),(12,43,29),(8,11,2)]
x.sort(key=lambda x:x[2],reverse=True)
x

[(12, 43, 29), (1, 4, 6), (8, 11, 2), (2, 8, 1)]

In [5]:
import json
import jsonlines

with open('dev-v2.0.jsonl', 'w') as outfile, open("../Downloads/dev-v2.0.json",'r') as JSON_file:
    for entry in JSON_file:
        json.dump(entry, outfile)
        outfile.write('\n')

### Search if any alphabets are present regex pattern search

In [6]:
import re
for each in ["1.0 ",'a 1.9']:
    if re.search('[A-Za-z]',each):
        print("Hi")
    else:
        print(each)

1.0 
Hi


### Make directory if not present

In [8]:
os.makedirs(OUT_DIR, exist_ok=True)

NameError: name 'os' is not defined

### [Ignore deprecation warnings](https://kite.com/python/answers/how-to-ignore-deprecation-warnings-in-python)

In [10]:
import warnings
warnings.filterwarnings("ignore")

### [Multidimentional array index using single dimentional array across  column](https://stackoverflow.com/questions/36350384/multi-dimensional-array-indexing-using-a-single-dimensional-array-in-python/36351043)

In [11]:
max_amount = insulin_data[np.arange(max_time_idx.shape[0]),max_time_idx.T].T

NameError: name 'insulin_data' is not defined