# Python Short cuts for scenarios

# List

#### Set to List

In [1]:
a = set([1,2,3,4,1,4])
list(a)
#a.tolist() #Doesn't work

[1, 2, 3, 4]

### zip - Change two values simultaneously in a single loop

In [2]:
alist = ['a1', 'a2', 'a3']
blist = ['b1', 'b2', 'b3']
for a, b in zip(alist, blist):
    print (a, b)

a1 b1
a2 b2
a3 b3


### Find the elements match in corresponding locations of two lists equal sized

In [3]:
a = [1,2,3,4,7,6]
b = [3,2,6,8,7,6]
[i for i,j in zip(a,b) if i==j]

[2, 7, 6]

In [4]:
### Checking List Equality
alist == blist

False

#### Flatten Multidimentional List to 1D list (Works fullly for list of lists)

In [5]:
import itertools
l = [[[0]],[6,7],[4,6,8],[[9],[80]]]
list(itertools.chain(*l))

[[0], 6, 7, 4, 6, 8, [9], [80]]

In [ ]:
# if 2-dimensional
result['id'] = [eachid for each in ids for eachid in each] 

# NUMPY

In [6]:
import numpy as np
na = np.array([[1,3,4,5],[4,6,1,7],[3,2,6,88]])

### Specific column selection 
https://stackoverflow.com/questions/8386675/extracting-specific-columns-in-numpy-array

In [7]:
print (na[:,1:3]) # columns from 1 upto 3-1
print (na[:,[1,3]]) #columns 1 and 3

[[3 4]
 [6 1]
 [2 6]]
[[ 3  5]
 [ 6  7]
 [ 2 88]]


### Select rows of a numpy array having a value in any column. Display any 3 specified columns
https://stackoverflow.com/questions/23911875/select-certain-rows-condition-met-but-only-some-columns-in-python-numpy

In [8]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,2,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  2 12]]


In [9]:
a[:,] == 2
#np.where(a[]==2)

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

### Number of Matches in two 1D array

In [10]:
goldY = np.array([1,2,1,1,2,1,3,3,3,3,2,1,2])
predY = np.array([1,2,3,1,1,1,3,1,3,3,2,1,1])
np.count_nonzero(predY == goldY)

9

### ARGMAX N

In [9]:
import numpy as np
a = np.array([4,5,2,1,8,0,3])
#Argsort orders from least to max values
a.argsort()[-3:][::-1]

array([4, 1, 0])

### ARGPARSE

In [11]:
import argparse

def main():
    parser = argparse.ArgumentParser()
    
    parser.add_argument("--eval_batch_size",default=16,type=int,required=False,help="Test batch size")
    parser.add_argument("--data_dir",default=None,type=str,required=True, help="Path of the Input test file")
    parser.add_argument("--no_cuda",default="False")
    parser.add_argument("--do_eval",action="store_true",help="Whether to use pretrained or not")
    
    args = parser.parse_args()
    
    print (args.eval_batch_size, args.data_dir, args.no_cuda, args.do_eval)

In [12]:
#Call by running ''' python filename.py --eval_batch_size 32 --do_eval --data_dir data/a/'''

### ARGMAX for LIST

In [13]:
p = [2,3,7,9,1,4,8,0]
maxp = max(p)
maxIdx = p.index(maxp)
print (maxIdx)

3


## DICTIONARY

#### Keys and values

In [14]:
a = {'a':1,'c':4,'b':3}
print(a.keys(),type(a.keys()),list(a.keys()))
print(a.values(),list(a.values()))

dict_keys(['a', 'c', 'b']) <class 'dict_keys'> ['a', 'c', 'b']
dict_values([1, 4, 3]) [1, 4, 3]


## UNICODE and STRING NORMALIZATION

In [15]:
# Turn a Unicode string to plain ASCII, thanks to
# https://stackoverflow.com/a/518232/2809427
def unicodeToAscii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
    )

# Lowercase, trim, and remove non-letter characters


def normalizeString(s):
    s = unicodeToAscii(s.lower().strip())
    s = re.sub(r"([.!?])", r" \1", s)
    s = re.sub(r"[^a-zA-Z.!?]+", r" ", s)
    return s

### Important Basics

In [3]:
a = "Hi"
a = 9 # allowed
b = "hello"
b[1]='i' #not allowed //String objects immutable

TypeError: 'str' object does not support item assignment

In [4]:
TestMode = True
def some_function():
  global TestMode
  TestMode = False
some_function()
print(TestMode) #<--Returns False For assigning a new value to a global variable from a function

False


In [8]:
a=9,2,3
print (a) # Returns tupple

(9, 2, 3)


In [13]:
# Numeric Operation
print(2//3) # Numeric division [floor]
print(2**3) # Exponentiation
print('A'*3) #Str repeatation
y = 'Abc'
print (y[:2],y[1:],y[:-2],y[-2:])
x = 'abc'
print(x[::-1]) #Reverse

0
8
AAA
Ab bc A bc
cba


In [21]:
#Garbage collection
import gc
collected_objects = gc.get_objects()
co = gc.collect()
print (co,collected_objects[0])

0 [<_ast.Expr object at 0x7fbe6808a828>]


### PATH Related

#### [Change the root path](https://stackoverflow.com/questions/1432924/python-change-the-scripts-working-directory-to-the-scripts-own-directory)

In [4]:
import os
print (os.getcwd())
os.chdir('/Users/kuntal/Python-cheat-sheets')
print (os.getcwd())
#This path should be relative to the root directory just set
embedding = "data/embeddings/pubmed_s100w10_min.bin"

/Users/kuntal/Python-cheat-sheets
/Users/kuntal/Python-cheat-sheets
